// ----------------------------------------------
// Polytechnique - INF584 "Image Synthesis"
//
// Base code for practical assignments.
//
// Copyright (C) 2022 Tamy Boubekeur
// All rights reserved.
// ----------------------------------------------
#pragma once
#include <glad/glad.h>
#include <string>

/// Executed whenever a debug message is generated by OpenGL, including the critical errors.
void APIENTRY debugMessageCallback (GLenum source,
        				   			GLenum type,
        				   			GLuint id,
        				   			GLenum severity,
        				   			GLsizei length,
        				   			const GLchar* message,
        				   			const void* userParam);

void exitOnCriticalError (const std::string & message);
